services:
  database:
    build:
      context: ./database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: movie123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  webapp:
    build:
      context: ./webapp
    ports:
      - "8080:80"
    depends_on:
      - database
    volumes:
      - ./webapp:/app

volumes:
  db_data:
